(registered 2023-09-18, last updated 2023-09-18)

Media type name: application

Media subtype name: vnd.mermaid

Required parameters: N/A.

Optional parameters: N/A.

Encoding considerations: binary

Security considerations: As the format allows embedding actions and
   images, it is possible to embed malicious code in the text.
   It is recommended to use a sandboxed environment to render the 
   diagram from untrusted sources.
   Sanitization of the input is also recommended.

   May contain URI links inside the diagram text, which is only used 
   in the output directly and not for any internal interpretations.

   Not compressed.

Interoperability considerations: The format is character-based, and
   applications exist on Web, Desktop and Mobile platforms which 
   render the format.

Published specification: https://mermaid.js.org/intro/#diagram-types
   includes examples of supported diagram types, and the links to
   complete syntax of individual diagrams.

Applications which use this media: Tools which render diagrams from
   text, popular markdown editors, GitHub, GitLab, etc.

   Detailed list available at
   https://mermaid.js.org/ecosystem/integrations.html

Fragment identifier considerations: N/A.

Restrictions on usage: N/A.

Additional information:

   1. Deprecated alias names for this type: N/A.
   2. Magic number(s): N/A.
   3. File extension(s): .mmd, .mermaid
   4. Macintosh file type code: N/A.
   5. Object Identifiers: N/A.
   6. Apple Uniform Type Identifier: org.js.mermaid conforms to 
      public.utf8-plain-text
   7. Windows Clipboard Name: Mermaid

Person to contact for further information:

   1. Name: Sidharth Vinod
   2. Email: iana&mermaid.js.org

Intended usage: COMMON

Author/Change controller: 

   Sidharth Vinod
   iana&mermaid.js.org