<?xml version="1.0" encoding="UTF-8"?>
<schema
  targetNamespace="https://gavinbrown.xyz/xmlns/epp/related-objects-1.0"
  xmlns:ro="https://gavinbrown.xyz/xmlns/epp/related-objects-1.0"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
  <annotation>
    <documentation>
      Extensible Provisioning Protocol v1.0 extension schema for
      related objects.
    </documentation>
  </annotation>

  <element name="info" type="ro:info" />
  <element name="infData" type="ro:infData" />

  <complexType name="info">
    <sequence>
      <element name="include" type="ro:include" />
    </sequence>
  </complexType>

  <complexType name="include">
    <all>
      <element name="registrant" minOccurs="0" maxOccurs="1" />
      <element name="contacts" minOccurs="0" maxOccurs="1" />
      <element name="orgs" minOccurs="0" maxOccurs="1" />
      <element name="ns" minOccurs="0" maxOccurs="1" />
      <element name="hosts" minOccurs="0" maxOccurs="1" />
      <element name="other" minOccurs="0" maxOccurs="1" />
    </all>
  </complexType>

  <complexType name="infData">
    <sequence>
      <!--
        note: a limitation of XSD 1.0 prevents forcing child elements to
        have the local name "infData", but the narrative of the
        specification makes it clear that this is required.
      -->
      <any namespace="##other" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>
</schema>
