on:
  schedule:
  - cron: "0 * * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rsync -avzH --del --exclude .git --exclude README.md --exclude SECURITY.md --exclude .github rsync.iana.org::assignments .
          git status
          git config --global user.email "lars@eggert.org"
          git config --global user.name "Lars Eggert"
          git add -A && git commit -a -m "$(date -u)" && git push || true
